stages:
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: php:${CICD_EXECUTION_SEQUENCE}
      registry: deltaapps/php
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment.yaml
